In [1]:
import numpy as np
import pandas as pd

In [2]:
cards_df = pd.read_csv("Cards_Data.csv")
cards_df.head()

,Card_ID,Customer_ID,Card_Type,Card_Network,Credit_Limit,Card_Status,Contactless,Card_Mode,Issue_Date,Expiry_Date
0,CARD500001,CUST100001,Gold,RuPay,587317,Active,Yes,Physical,2021-04-24,2026-04-24
1,CARD500002,CUST100002,Silver,Visa,150720,Active,Yes,Virtual,2020-06-30,2025-06-30
2,CARD500003,CUST100003,Gold,RuPay,631005,Active,Yes,Physical,2022-04-04,2027-04-04
3,CARD500004,CUST100004,Silver,Mastercard,285015,Expired,Yes,Virtual,2020-07-21,2025-07-21
4,CARD500005,CUST100005,Gold,Mastercard,348591,Active,Yes,Physical,2024-07-24,2029-07-24

In [3]:
cards_df.shape

(32457, 10)

In [4]:
print(cards_df[cards_df.duplicated(subset=['Card_ID'])])

Empty DataFrame
Columns: [Card_ID, Customer_ID, Card_Type, Card_Network, Credit_Limit, Card_Status, Contactless, Card_Mode, Issue_Date, Expiry_Date]
Index: []

In [5]:
customers_df = pd.read_csv("Cusmtomer_data.csv")
customers_df.head()

,Customer_ID,Customer_Name,Gender,Age,Marital_Status,Occupation,Annual_Income,Customer_Segment,State,City,Account_Type,Customer_Since
0,CUST100001,Omaja Majumdar,Female,27,Single,Police Officer,1167132,Gold,Uttar Pradesh,Agra,Savings,2017-11-13
1,CUST100002,Jason Agrawal,Female,41,Married,Teacher,493532,Standard,Madhya Pradesh,Ujjain,Salary,2020-05-05
2,CUST100003,Amrita Dora,Male,61,Divorsed,Business,1862614,Platinum,Assam,Silchar,Savings,2023-08-23
3,CUST100004,Radhika Batra,Male,26,Single,Software Engineer,808153,Gold,Uttar Pradesh,Ghaziabad,Salary,2018-05-21
4,CUST100005,Gautam Mukhopadhyay,Female,24,Single,Software Engineer,1581447,Platinum,Rajasthan,Jodhpur,Salary,2017-04-16

In [6]:
customers_df.shape

(25000, 12)

In [7]:
print(customers_df[customers_df.duplicated(subset=['Customer_ID'])])

Empty DataFrame
Columns: [Customer_ID, Customer_Name, Gender, Age, Marital_Status, Occupation, Annual_Income, Customer_Segment, State, City, Account_Type, Customer_Since]
Index: []

In [8]:
merchants_df = pd.read_csv("merchant_table.csv")
merchants_df.head()

,Merchant_ID,Merchant_Name,Merchant_Category,State,City,Merchant_Risk_Level,Merchant_Rating,Merchant_Status,Merchant_Since
0,MER100001,Paytm Utilities,Utilities,Haryana,Gurugram,Medium,4.8,Active,2012-07-29
1,MER100002,Coursera,Education,Bihar,Patna,Low,4.3,Active,2008-03-09
2,MER100003,Redbus,Travel,Bihar,Muzaffarpur,Low,4.7,Active,2006-08-12
3,MER100004,Air India,Airline,Tamil Nadu,Salem,Low,3.6,Active,2008-03-30
4,MER100005,IndiGo,Airline,Punjab,Jalandhar,Medium,4.1,Active,2007-07-18

In [9]:
merchants_df.shape

(500, 9)

In [10]:
print(merchants_df[merchants_df.duplicated(subset=['Merchant_ID'])])

Empty DataFrame
Columns: [Merchant_ID, Merchant_Name, Merchant_Category, State, City, Merchant_Risk_Level, Merchant_Rating, Merchant_Status, Merchant_Since]
Index: []

In [11]:
transactions_df= pd.read_csv("Transaction_Data_250k.csv")
transactions_df.head()

,Transaction_ID,Customer_ID,Card_ID,Merchant_ID,Transaction_Date,Transaction_Time,Transaction_Amount,Payment_Method,Transaction_Channel,Device_Type,Transaction_Status,Is_International,Fraud_Flag,Fraud_Reason,Merchant_Risk_Level,Merchant_Category,Customer_State,Customer_City,Merchant_State,Merchant_City
0,TXN1000001,CUST100660,CARD500875,MER100380,2024-03-03,05:50:10,21748.02,Debit Card,Mobile App,Android Mobile,Successful,1,0,NaN,Low,Hotel,Tamil Nadu,Madurai,Tamil Nadu,Salem
1,TXN1000002,CUST111388,CARD514772,MER100017,2023-11-08,06:55:15,9960.60,Debit Card,POS,POS Terminal,Successful,0,0,NaN,Low,Travel,Kerala,Kollam,Haryana,Nuh
2,TXN1000003,CUST115872,CARD520625,MER100143,2023-01-11,02:17:28,838.61,Debit Card,ATM,ATM Machine,Successful,0,0,NaN,Low,Food Delivery,Uttar Pradesh,Agra,West Bengal,Kolkata
3,TXN1000004,CUST109049,CARD511773,MER100053,2023-05-25,01:48:56,52694.99,Credit Card,POS,POS Terminal,Successful,0,0,NaN,Low,Financial Services,Punjab,Ludhiana,Madhya Pradesh,Indore
4,TXN1000005,CUST114459,CARD518771,MER100064,2023-10-22,00:23:32,1043.40,Debit Card,Online Web,Android Mobile,Successful,0,0,NaN,Low,Entertainment,Maharashtra,Thane,Madhya Pradesh,Jabalpur

In [12]:
transactions_df.shape

(250000, 20)

In [13]:
cards_df = cards_df.drop(columns=['Customer_ID'])

In [14]:
transactions_df = pd.merge(transactions_df, cards_df, on='Card_ID', how='left')

In [15]:
transactions_df.head()

,Transaction_ID,Customer_ID,Card_ID,Merchant_ID,Transaction_Date,Transaction_Time,Transaction_Amount,Payment_Method,Transaction_Channel,Device_Type,...,Merchant_State,Merchant_City,Card_Type,Card_Network,Credit_Limit,Card_Status,Contactless,Card_Mode,Issue_Date,Expiry_Date
0,TXN1000001,CUST100660,CARD500875,MER100380,2024-03-03,05:50:10,21748.02,Debit Card,Mobile App,Android Mobile,...,Tamil Nadu,Salem,Silver,Mastercard,158503,Active,Yes,Virtual,2021-09-07,2026-09-07
1,TXN1000002,CUST111388,CARD514772,MER100017,2023-11-08,06:55:15,9960.60,Debit Card,POS,POS Terminal,...,Haryana,Nuh,Gold,Mastercard,391734,Active,Yes,Physical,2023-09-23,2028-09-23
2,TXN1000003,CUST115872,CARD520625,MER100143,2023-01-11,02:17:28,838.61,Debit Card,ATM,ATM Machine,...,West Bengal,Kolkata,Platinum,Visa,1389274,Active,Yes,Physical,2020-08-22,2025-08-22
3,TXN1000004,CUST109049,CARD511773,MER100053,2023-05-25,01:48:56,52694.99,Credit Card,POS,POS Terminal,...,Madhya Pradesh,Indore,Platinum,Mastercard,1411749,Active,Yes,Physical,2020-10-31,2025-10-31
4,TXN1000005,CUST114459,CARD518771,MER100064,2023-10-22,00:23:32,1043.40,Debit Card,Online Web,Android Mobile,...,Madhya Pradesh,Jabalpur,Silver,RuPay,267163,Active,Yes,Virtual,2019-07-16,2024-07-16

In [16]:
transactions_df.shape

(250000, 28)

In [17]:
transactions_df[['Card_Type','Card_Network','Credit_Limit','Card_Status']].isnull().sum()

Card_Type       0
Card_Network    0
Credit_Limit    0
Card_Status     0
dtype: int64

In [18]:
customers_df = customers_df.drop(columns=['State', 'City'])
customers_df.head()

,Customer_ID,Customer_Name,Gender,Age,Marital_Status,Occupation,Annual_Income,Customer_Segment,Account_Type,Customer_Since
0,CUST100001,Omaja Majumdar,Female,27,Single,Police Officer,1167132,Gold,Savings,2017-11-13
1,CUST100002,Jason Agrawal,Female,41,Married,Teacher,493532,Standard,Salary,2020-05-05
2,CUST100003,Amrita Dora,Male,61,Divorsed,Business,1862614,Platinum,Savings,2023-08-23
3,CUST100004,Radhika Batra,Male,26,Single,Software Engineer,808153,Gold,Salary,2018-05-21
4,CUST100005,Gautam Mukhopadhyay,Female,24,Single,Software Engineer,1581447,Platinum,Salary,2017-04-16

In [19]:
transactions_df = pd.merge(transactions_df, customers_df, on='Customer_ID', how='left')

In [20]:
transactions_df.head()

,Transaction_ID,Customer_ID,Card_ID,Merchant_ID,Transaction_Date,Transaction_Time,Transaction_Amount,Payment_Method,Transaction_Channel,Device_Type,...,Expiry_Date,Customer_Name,Gender,Age,Marital_Status,Occupation,Annual_Income,Customer_Segment,Account_Type,Customer_Since
0,TXN1000001,CUST100660,CARD500875,MER100380,2024-03-03,05:50:10,21748.02,Debit Card,Mobile App,Android Mobile,...,2026-09-07,Sai Ganguly,Female,23,Single,Nurse,753978,Gold,Savings,2025-03-28
1,TXN1000002,CUST111388,CARD514772,MER100017,2023-11-08,06:55:15,9960.60,Debit Card,POS,POS Terminal,...,2028-09-23,Devika Tak,Male,44,Married,Chartered Accountant,3874640,Platinum,Savings,2016-11-22
2,TXN1000003,CUST115872,CARD520625,MER100143,2023-01-11,02:17:28,838.61,Debit Card,ATM,ATM Machine,...,2025-08-22,Luke Kamdar,Female,29,Single,Lawyer,3199891,Platinum,Salary,2026-03-05
3,TXN1000004,CUST109049,CARD511773,MER100053,2023-05-25,01:48:56,52694.99,Credit Card,POS,POS Terminal,...,2025-10-31,Brijesh Pall,Female,51,Married,Doctor,2979987,Platinum,Salary,2025-12-11
4,TXN1000005,CUST114459,CARD518771,MER100064,2023-10-22,00:23:32,1043.40,Debit Card,Online Web,Android Mobile,...,2024-07-16,Ayaan Bava,Female,42,Married,Teacher,380070,Standard,Savings,2020-03-22

In [21]:
transactions_df[['Annual_Income', 'Occupation', 'Customer_Segment']].isnull().sum()

Annual_Income       0
Occupation          0
Customer_Segment    0
dtype: int64

In [22]:
merchants_df_trimmed = merchants_df[['Merchant_ID', 'Merchant_Name', 'Merchant_Rating', 'Merchant_Status', 'Merchant_Since']]
merchants_df_trimmed.head()

  Merchant_ID    Merchant_Name  Merchant_Rating Merchant_Status Merchant_Since
0   MER100001  Paytm Utilities              4.8          Active     2012-07-29
1   MER100002         Coursera              4.3          Active     2008-03-09
2   MER100003           Redbus              4.7          Active     2006-08-12
3   MER100004        Air India              3.6          Active     2008-03-30
4   MER100005           IndiGo              4.1          Active     2007-07-18

In [23]:
transactions_df = pd.merge(transactions_df, merchants_df_trimmed, on='Merchant_ID', how='left')
transactions_df.head()

,Transaction_ID,Customer_ID,Card_ID,Merchant_ID,Transaction_Date,Transaction_Time,Transaction_Amount,Payment_Method,Transaction_Channel,Device_Type,...,Marital_Status,Occupation,Annual_Income,Customer_Segment,Account_Type,Customer_Since,Merchant_Name,Merchant_Rating,Merchant_Status,Merchant_Since
0,TXN1000001,CUST100660,CARD500875,MER100380,2024-03-03,05:50:10,21748.02,Debit Card,Mobile App,Android Mobile,...,Single,Nurse,753978,Gold,Savings,2025-03-28,Taj Hotels,4.3,Active,2021-04-20
1,TXN1000002,CUST111388,CARD514772,MER100017,2023-11-08,06:55:15,9960.60,Debit Card,POS,POS Terminal,...,Married,Chartered Accountant,3874640,Platinum,Savings,2016-11-22,Redbus,4.1,Active,2022-03-03
2,TXN1000003,CUST115872,CARD520625,MER100143,2023-01-11,02:17:28,838.61,Debit Card,ATM,ATM Machine,...,Single,Lawyer,3199891,Platinum,Salary,2026-03-05,Pizza Hut,4.0,Active,2019-06-11
3,TXN1000004,CUST109049,CARD511773,MER100053,2023-05-25,01:48:56,52694.99,Credit Card,POS,POS Terminal,...,Married,Doctor,2979987,Platinum,Salary,2025-12-11,PhonePe,4.4,Active,2011-06-25
4,TXN1000005,CUST114459,CARD518771,MER100064,2023-10-22,00:23:32,1043.40,Debit Card,Online Web,Android Mobile,...,Married,Teacher,380070,Standard,Savings,2020-03-22,Netflix India,4.9,Active,2011-04-02

In [24]:
transactions_df[['Merchant_ID', 'Merchant_Name', 'Merchant_Rating', 'Merchant_Status', 'Merchant_Since']].isnull().sum()

Merchant_ID        0
Merchant_Name      0
Merchant_Rating    0
Merchant_Status    0
Merchant_Since     0
dtype: int64

In [25]:
transactions_df['Fraud_Flag'].value_counts(normalize=True)

Fraud_Flag
0    0.946108
1    0.053892
Name: proportion, dtype: float64

In [26]:
transactions_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 41 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Transaction_ID       250000 non-null  object
 1   Customer_ID          250000 non-null  object
 2   Card_ID              250000 non-null  object
 3   Merchant_ID          250000 non-null  object
 4   Transaction_Date     250000 non-null  object
 5   Transaction_Time     250000 non-null  object
 6   Transaction_Amount   250000 non-null  float64
 7   Payment_Method       250000 non-null  object
 8   Transaction_Channel  250000 non-null  object
 9   Device_Type          250000 non-null  object
 10  Transaction_Status   250000 non-null  object
 11  Is_International     250000 non-null  int64
 12  Fraud_Flag           250000 non-null  int64
 13  Fraud_Reason         13473 non-null   object
 14  Merchant_Risk_Level  250000 non-null  object
 15  Merchant_Category    250000 non-null  object
 16  Customer_State       250000 non-null  object
 17  Customer_City        250000 non-null  object
 18  Merchant_State       250000 non-null  object
 19  Merchant_City        250000 non-null  object
 20  Card_Type            250000 non-null  object
 21  Card_Network         250000 non-null  object
 22  Credit_Limit         250000 non-null  int64
 23  Card_Status          250000 non-null  object
 24  Contactless          250000 non-null  object
 25  Card_Mode            250000 non-null  object
 26  Issue_Date           250000 non-null  object
 27  Expiry_Date          250000 non-null  object
 28  Customer_Name        250000 non-null  object
 29  Gender               250000 non-null  object
 30  Age                  250000 non-null  int64
 31  Marital_Status       250000 non-null  object
 32  Occupation           250000 non-null  object
 33  Annual_Income        250000 non-null  int64
 34  Customer_Segment     250000 non-null  object
 35  Account_Type         250000 non-null  object
 36  Customer_Since       250000 non-null  object
 37  Merchant_Name        250000 non-null  object
 38  Merchant_Rating      250000 non-null  float64
 39  Merchant_Status      250000 non-null  object
 40  Merchant_Since       250000 non-null  object
dtypes: float64(2), int64(5), object(34)
memory usage: 78.2+ MB

In [27]:
transactions_df['Transaction_Date'] = pd.to_datetime(transactions_df['Transaction_Date'])

In [28]:
transactions_df['Issue_Date'] = pd.to_datetime(transactions_df['Issue_Date'])

In [29]:
transactions_df['Expiry_Date'] = pd.to_datetime(transactions_df['Expiry_Date'])

In [30]:
transactions_df['Customer_Since'] = pd.to_datetime(transactions_df['Customer_Since'])

In [31]:
transactions_df['Merchant_Since'] = pd.to_datetime(transactions_df['Merchant_Since'])

In [32]:
transactions_df[['Transaction_Date', 'Issue_Date', 'Expiry_Date', 'Customer_Since', 'Merchant_Since']].dtypes

Transaction_Date    datetime64[ns]
Issue_Date          datetime64[ns]
Expiry_Date         datetime64[ns]
Customer_Since      datetime64[ns]
Merchant_Since      datetime64[ns]
dtype: object

In [33]:
transactions_df['Transaction_Time'] = pd.to_datetime(transactions_df['Transaction_Time'], format='%H:%M:%S').dt.time

In [34]:
transactions_df['Transaction_Hour'] = transactions_df['Transaction_Time'].apply(lambda x: x.hour)

In [35]:
transactions_df[['Transaction_Time', 'Transaction_Hour']].head()

  Transaction_Time  Transaction_Hour
0         05:50:10                 5
1         06:55:15                 6
2         02:17:28                 2
3         01:48:56                 1
4         00:23:32                 0

In [36]:
transactions_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 42 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Transaction_ID       250000 non-null  object
 1   Customer_ID          250000 non-null  object
 2   Card_ID              250000 non-null  object
 3   Merchant_ID          250000 non-null  object
 4   Transaction_Date     250000 non-null  datetime64[ns]
 5   Transaction_Time     250000 non-null  object
 6   Transaction_Amount   250000 non-null  float64
 7   Payment_Method       250000 non-null  object
 8   Transaction_Channel  250000 non-null  object
 9   Device_Type          250000 non-null  object
 10  Transaction_Status   250000 non-null  object
 11  Is_International     250000 non-null  int64
 12  Fraud_Flag           250000 non-null  int64
 13  Fraud_Reason         13473 non-null   object
 14  Merchant_Risk_Level  250000 non-null  object
 15  Merchant_Category    250000 non-null  object
 16  Customer_State       250000 non-null  object
 17  Customer_City        250000 non-null  object
 18  Merchant_State       250000 non-null  object
 19  Merchant_City        250000 non-null  object
 20  Card_Type            250000 non-null  object
 21  Card_Network         250000 non-null  object
 22  Credit_Limit         250000 non-null  int64
 23  Card_Status          250000 non-null  object
 24  Contactless          250000 non-null  object
 25  Card_Mode            250000 non-null  object
 26  Issue_Date           250000 non-null  datetime64[ns]
 27  Expiry_Date          250000 non-null  datetime64[ns]
 28  Customer_Name        250000 non-null  object
 29  Gender               250000 non-null  object
 30  Age                  250000 non-null  int64
 31  Marital_Status       250000 non-null  object
 32  Occupation           250000 non-null  object
 33  Annual_Income        250000 non-null  int64
 34  Customer_Segment     250000 non-null  object
 35  Account_Type         250000 non-null  object
 36  Customer_Since       250000 non-null  datetime64[ns]
 37  Merchant_Name        250000 non-null  object
 38  Merchant_Rating      250000 non-null  float64
 39  Merchant_Status      250000 non-null  object
 40  Merchant_Since       250000 non-null  datetime64[ns]
 41  Transaction_Hour     250000 non-null  int64
dtypes: datetime64[ns](5), float64(2), int64(6), object(29)
memory usage: 80.1+ MB

In [37]:
transactions_df.duplicated().sum()

np.int64(0)

In [38]:
transactions_df['Marital_Status'].unique()

array(['Single', 'Married', 'Divorsed'], dtype=object)

In [39]:
transactions_df.describe()

,Transaction_Date,Transaction_Amount,Is_International,Fraud_Flag,Credit_Limit,Issue_Date,Expiry_Date,Age,Annual_Income,Customer_Since,Merchant_Rating,Merchant_Since,Transaction_Hour
count,250000,2.500000e+05,250000.000000,250000.000000,2.500000e+05,250000,250000,250000.000000,2.500000e+05,250000,250000.000000,250000,250000.000000
mean,2024-11-14 06:12:02.995200,1.660753e+04,0.050288,0.053892,4.435445e+05,2022-07-20 16:00:57.484800,2027-07-20 21:55:23.980800,41.834120,1.608372e+06,2021-07-09 05:47:11.385599744,4.292130,2016-05-22 10:18:33.984000,11.413756
min,2023-01-01 00:00:00,1.000000e+02,0.000000,0.000000,5.000200e+04,2018-07-20 00:00:00,2023-07-20 00:00:00,18.000000,2.000000e+00,2016-07-19 00:00:00,3.500000,2006-07-22 00:00:00,0.000000
25%,2023-11-11 00:00:00,1.000000e+03,0.000000,0.000000,1.614910e+05,2020-07-18 00:00:00,2025-07-18 00:00:00,31.000000,5.702060e+05,2018-12-26 00:00:00,4.000000,2011-05-07 00:00:00,5.000000
50%,2024-12-01 00:00:00,3.155260e+03,0.000000,0.000000,2.965890e+05,2022-07-25 00:00:00,2027-07-25 00:00:00,41.000000,9.631030e+05,2021-07-04 00:00:00,4.300000,2016-09-10 00:00:00,11.000000
75%,2025-11-27 00:00:00,1.830991e+04,0.000000,0.000000,6.157200e+05,2024-07-23 00:00:00,2029-07-23 00:00:00,53.000000,1.861271e+06,2024-01-05 00:00:00,4.700000,2021-09-06 00:00:00,17.000000
max,2026-08-18 00:00:00,1.887057e+06,1.000000,1.000000,1.499927e+06,2026-07-19 00:00:00,2031-07-19 00:00:00,70.000000,9.999931e+06,2026-07-19 00:00:00,5.000000,2026-07-18 00:00:00,23.000000
std,NaN,5.342157e+04,0.218539,0.225805,3.686547e+05,NaN,NaN,13.071616,1.732134e+06,NaN,0.416867,NaN,6.966145

In [40]:
transactions_df['Marital_Status'] = transactions_df['Marital_Status'].replace('Divorsed', 'Divorced')

In [41]:
transactions_df[transactions_df['Annual_Income'] < 10000][['Customer_ID','Annual_Income']]

       Customer_ID  Annual_Income
163     CUST118060           3570
208     CUST104248           7552
1049    CUST109474           7415
1168    CUST108552           3864
1277    CUST116748           1316
...            ...            ...
249191  CUST111363            395
249433  CUST103790           1408
249460  CUST123793           9504
249706  CUST102873           3906
249851  CUST119798           3540

[968 rows x 2 columns]

In [42]:
transactions_df[transactions_df['Transaction_Date'] > '2026-07-31'].shape

(505, 42)

In [43]:
transactions_df['Income_Data_Issue'] = np.where(transactions_df['Annual_Income'] < 10000, 1, 0)

income_median = transactions_df.loc[transactions_df['Income_Data_Issue'] == 0, 'Annual_Income'].median()

transactions_df['Annual_Income'] = np.where(
    transactions_df['Income_Data_Issue'] == 1,
    income_median,
    transactions_df['Annual_Income']
)

In [44]:

transactions_df['Annual_Income'].min()

10004.0

In [45]:
transactions_df['Income_Data_Issue'].value_counts()

Income_Data_Issue
0    249032
1       968
Name: count, dtype: int64

In [64]:
transactions_df.groupby('Transaction_Channel')['Fraud_Flag'].agg(['mean', 'count']).sort_values(by='mean', ascending=False)

                         mean   count
Transaction_Channel
Mobile App           0.055592   64991
Online Web           0.055231   24823
ATM                  0.053180   39902
POS                  0.052933  120284

In [66]:
transactions_df.groupby('Transaction_Hour')['Fraud_Flag'].agg(['mean', 'count']).sort_values(by='mean', ascending=False)

                      mean  count
Transaction_Hour
0                 0.058048  12059
2                 0.056918  10278
6                 0.056613  10457
13                0.056371  10360
4                 0.055893  10377
12                0.055809  10321
20                0.055691  10253
11                0.055246  10408
21                0.054584  10296
5                 0.054499  10459
8                 0.054490  10222
15                0.054438  10195
23                0.053919  10423
18                0.053319  10259
1                 0.053219  10391
10                0.053168  10401
9                 0.053002  10377
22                0.052300  10325
19                0.051990  10502
3                 0.051465  10376
16                0.050804  10255
7                 0.050655  10305
14                0.050565  10264
17                0.049727  10437

In [68]:
transactions_df.groupby('Card_Status')['Fraud_Flag'].agg(['mean', 'count']).sort_values(by='mean', ascending=False)

                 mean   count
Card_Status
Blocked      1.000000    1591
Expired      1.000000    2470
Lost         1.000000     848
Active       0.034942  245091

In [76]:
active_df = transactions_df[transactions_df['Card_Status'] == 'active']
active_df = transactions_df[transactions_df['Card_Status'] == 'Active']
active_df.head()

Empty DataFrame
Columns: [Transaction_ID, Customer_ID, Card_ID, Merchant_ID, Transaction_Date, Transaction_Time, Transaction_Amount, Payment_Method, Transaction_Channel, Device_Type, Transaction_Status, Is_International, Fraud_Flag, Fraud_Reason, Merchant_Risk_Level, Merchant_Category, Customer_State, Customer_City, Merchant_State, Merchant_City, Card_Type, Card_Network, Credit_Limit, Card_Status, Contactless, Card_Mode, Issue_Date, Expiry_Date, Customer_Name, Gender, Age, Marital_Status, Occupation, Annual_Income, Customer_Segment, Account_Type, Customer_Since, Merchant_Name, Merchant_Rating, Merchant_Status, Merchant_Since, Transaction_Hour, Income_Data_Issue]
Index: []

[0 rows x 43 columns]